# Generated by Django 5.1.3 on 2024-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En reparación', 'En reparación'), ('Descartada', 'Descartada')], max_length=20)),
            ],
        ),
    ]
