# Generated by Django 5.1.3 on 2024-11-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_computadora_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='responsable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
