# Generated by Django 5.1.3 on 2024-11-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_computadora_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='responsable',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
