# Generated by Django 5.1.3 on 2024-11-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_computadora_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='usuario',
        ),
    ]
