# Generated by Django 5.1.3 on 2024-11-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_computadora_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='licencia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
